apiVersion: v1
kind: Service
metadata:
  name: casestudyapi-service-unhealthy
  namespace: casestudy
spec:
  type: LoadBalancer
  selector:
    app: casestudyapi-unhealthy
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 8000
