apiVersion: v1
kind: Service
metadata:
  name: casestudyapi-service
  namespace: casestudy
spec:
  type: LoadBalancer
  selector:
    app: casestudyapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
